### PR TITLE
Minor improvements

### PR DESCRIPTION
**Pull request by zhuxb711**
1. Add mechanism to bypass Https certificate verification.
2. Make the datetime more human friendly in the log.

## Summary by CodeRabbit

- **New Features**
	- Introduced an option to skip HTTPS certificate verification for specific scenarios, enhancing flexibility for development and testing environments.

- **Documentation**
	- Updated documentation to include the new `API_VERIFY_HTTPS_CERT` environment variable and provided further clarification on the `BAN_WITHOUT_RADIO_CHECK` variable.

- **Bug Fixes**
	- Improved the banning mechanism by refining the conditions based on progress and uploaded size.

- **Refactor**
	- Enhanced the `start` method for better exception handling and re-login processes.
	- Updated session initialization to accommodate the new HTTPS certificate verification setting.

### CODE REVIEW

**Comment by Ghost-chu** [comment]
LGTM, but this repostory has been replaced by https://github.com/Ghost-chu/PeerBanHelper

**Comment by zhuxb711** [comment]
Thanks for the remind, as this repo is not being marked as Archive so I think it's still active. 
Whatever, [PeerBanHelper](https://github.com/Ghost-chu/PeerBanHelper) is to heavy for simple use so I think this repo is just fine due to memory pressure and other concerns. Simple and easy for common case. haha.

**Comment by zhuxb711** [comment]
Thanks, and hope you would release a new version for this enhancement.

**Comment by Ghost-chu** [comment]
There are still some issues with this script that does not automatically log you back in after your login has expired. I plan to release a new version after fixing this issue, but I don't have enough time right now. Will do that when I get free time.

**Comment by zhuxb711** [comment]
> There are still some issues with this script that does not automatically log you back in after your login has expired. I plan to release a new version after fixing this issue, but I don't have enough time right now. Will do that when I get free time.

So what is the problem, though I'm a new bird in python, maybe I could take a look at that

**Pull request merged**
